// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DodavanjeproizvodaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void dodavanjeproizvoda() {
    driver.get("http://localhost:8080/trgovinavujovic/index");
    driver.manage().window().setSize(new Dimension(974, 1050));
    driver.findElement(By.id("email")).sendKeys("jovan");
    driver.findElement(By.id("password")).sendKeys("test");
    driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
    {
      WebElement element = driver.findElement(By.linkText("Proizvodi"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Proizvodi")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".my-5 > .btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".my-5 > .btn")).click();
    driver.findElement(By.id("naziv")).click();
    driver.findElement(By.id("naziv")).sendKeys("nov proizvod");
    driver.findElement(By.id("cena")).sendKeys("150");
    driver.findElement(By.id("tezina")).sendKeys("150");
    driver.findElement(By.id("opis")).sendKeys("Kratak opis");
    driver.findElement(By.id("rokTrajanja")).sendKeys("12/12/2020");
    driver.findElement(By.id("kolicinaNaStanju")).click();
    driver.findElement(By.cssSelector("body")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-primary"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("kolicinaNaStanju")).sendKeys("500");
    driver.findElement(By.cssSelector(".btn-primary")).click();
  }
}
